                                                 Basic Numpy Exercises 
                                               Compiled by: Dr. Noman Islam

#### 1. Generate a 1D NumPy array containing numbers from -2 to 2 in increments of 0.2. Use optional start and step arguments of np.arange() function.

In [3]:
import numpy as np
arr1 = np.arange(-2,2,0.2,)
arr1

array([-2.0000000e+00, -1.8000000e+00, -1.6000000e+00, -1.4000000e+00,
       -1.2000000e+00, -1.0000000e+00, -8.0000000e-01, -6.0000000e-01,
       -4.0000000e-01, -2.0000000e-01, -4.4408921e-16,  2.0000000e-01,
        4.0000000e-01,  6.0000000e-01,  8.0000000e-01,  1.0000000e+00,
        1.2000000e+00,  1.4000000e+00,  1.6000000e+00,  1.8000000e+00])

#### 2. Generate another 1D NumPy array containing 11 equally spaced values between 0.5 and 1.5. Extract every second element of the array

In [9]:
arr2 = np.linspace(0.5,1.5,11)
arr2

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5])

#### 3. Create a 4x4 array with arbitrary values.Extract every element from the second row.


In [14]:
arr=np.arange(0,16).reshape((4,4))
display(arr)
arr[1,:]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([4, 5, 6, 7])

#### 4. Extract every element from the third column

In [15]:
arr[2,:]

array([ 8,  9, 10, 11])

#### 5. Assign a value of 0.21 to upper left 2x2 subarray.

In [6]:
import numpy as np
arr3= np.arange(1,5,1,float).reshape(2,2)
display(arr3)

arr3[0,0]=0.21

arr3

np.savetxt("exercise1_4.dat",arr3)

array([[1., 2.],
       [3., 4.]])

#### 6. Read an 2D array from the file exercise1_4.dat. You can usethe function np.loadtxt():
data = np.loadtxt(‘exercise1_4.dat’)

#### Split the array into four subblocks (upper left, upper right, lower left, lower right) using np.split(). Construct then the full array again with np.concatenate(). You can visualize the various arrays with matplotlib’s imshow(), i.e. import pylab pylab.imshow(data)

In [10]:
arr4=np.loadtxt('exercise1_4.dat')

np.split(arr4,[2,2])

arr4

array([[0.21, 2.  ],
       [3.  , 4.  ]])

In [11]:
np.concatenate(arr4)

array([0.21, 2.  , 3.  , 4.  ])